"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$all
"""

add_newline = true
aws.disabled = true
azure.disabled = true
gcloud.disabled = true

[username]
show_always = true
format = "[$user@]($style)"
style_user = "white"
style_root = "red"

[hostname]
ssh_only = false
trim_at = ""
style = "cyan"
ssh_symbol = " üåê"
format = '[$hostname$ssh_symbol]($style) '

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 1
style = "white"
